// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swjkkcqvmhsyrwplqbaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3amtrY3F2bWhzeXJ3cGxxYmFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MDc3NjgsImV4cCI6MjA2MDk4Mzc2OH0.DZK-H7C5zOb_KQVRUWD_676CH_H06luGR7aFO5VIl2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);